#!/usr/bin/env bash
#
# Permit to launch a test environment for Makefly
#

# To be done:
# 10/ Create test directory if no one
# 20/ Pull each needed repo (makefly one, makefly-devtools one)
# 25/ Clean up resulted files, repos, etc.
# 30/ Launch tests
# 40/ Create a result
# 50/ Publish this result

#####
## VARIABLES
###

BASE="/git"
TESTDIR="${BASE}/makefly_tests"
RESULTDIR="${TESTDIR}/result"
REPO="${BASE}/repositories/blogbox/makefly.git"
REPO_DEV="${BASE}/repositories/blogbox/makefly-devtools.git"
PUBLISH_DIR="${BASE}/public_html"

#####
## TESTS
###

# create testing directory
if ! test -d ${TESTDIR}
then
  mkdir ${TESTDIR} || exit 1
fi

# delete makefly repository if exists
if test -d "${TESTDIR}/makefly"
then
  rm -rf ${TESTDIR}/makefly
fi

# delete makefly developer tools repository if exists
if test -d "${TESTDIR}/makefly-devtools"
then
  rm -rf ${TESTDIR}/makefly-devtools
fi

# create result directory if it doesn't exist
if ! test -d "${RESULTDIR}"
then
  mkdir ${RESULTDIR} || exit 1
fi

#####
## BEGIN
###

# fetch repos
git clone ${REPO} ${TESTDIR}/makefly || exit 1
git clone ${REPO_DEV} ${TESTDIR}/makefly-devtools || exit 1

# go to test directory
cd ${TESTDIR}/makefly-devtools/tests
# launch test
MAKEOBJDIR=${TESTDIR}/makefly-devtools/tests main=${TESTDIR}/makefly result=${RESULTDIR} pmake > /dev/null || exit 1
# generate webpage
cd ${TESTDIR}/makefly-devtools/tests/result && RESULTDIR=${RESULTDIR} ./make_webpage.sh
# publish result
cp ${RESULTDIR}/result.html ${PUBLISH_DIR}/index.html
cp -r css/ ${PUBLISH_DIR}/
cp -r js/ ${PUBLISH_DIR}/
for i in `ls ${RESULTDIR}/*.rc`; do
  cp -f ${i} ${PUBLISH_DIR}/
done

#####
## END
###

exit 0
